// Code generated by protoc-gen-go.
// source: login.proto
// DO NOT EDIT!

/*
Package login is a generated protocol buffer package.

It is generated from these files:
	login.proto

It has these top-level messages:
	LoginRequest
	LoginResponse
*/
package login

import proto "github.com/hailocab/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

// For our mock login service we'll allow a username, password and
// optional 'remember me' boolean
type LoginRequest struct {
	Username   string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password   string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	RememberMe bool   `protobuf:"varint,3,opt,name=rememberMe" json:"rememberMe,omitempty"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}

// The response from logging in
type LoginResponse struct {
	Id           string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	SessionToken string `protobuf:"bytes,2,opt,name=sessionToken" json:"sessionToken,omitempty"`
	RefreshToken string `protobuf:"bytes,3,opt,name=refreshToken" json:"refreshToken,omitempty"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}

func init() {
}
