// Code generated by protoc-gen-go.
// source: subscribe.proto
// DO NOT EDIT!

/*
Package subscribe is a generated protocol buffer package.

It is generated from these files:
	subscribe.proto

It has these top-level messages:
	Subscribe
*/
package subscribe

import proto "github.com/hailocab/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

// When we subscribe or are subscribed to, we expect to receive this
// payload
type Subscribe struct {
	Name        string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Host        string `protobuf:"bytes,3,opt,name=host" json:"host,omitempty"`
	Port        string `protobuf:"bytes,4,opt,name=port" json:"port,omitempty"`
}

func (m *Subscribe) Reset()         { *m = Subscribe{} }
func (m *Subscribe) String() string { return proto.CompactTextString(m) }
func (*Subscribe) ProtoMessage()    {}

func init() {
}
